PERMISSIONS = {
    'access.role.view': {
        'name': 'View roles',
        'module': 'access',
        'resource': 'role',
        'action': 'view',
        'description': 'Allows viewing access roles.',
    },
    'access.role.create': {
        'name': 'Create roles',
        'module': 'access',
        'resource': 'role',
        'action': 'create',
        'description': 'Allows creating access roles.',
    },
    'access.role.update': {
        'name': 'Update roles',
        'module': 'access',
        'resource': 'role',
        'action': 'update',
        'description': 'Allows updating access roles.',
    },
    'access.role.delete': {
        'name': 'Delete roles',
        'module': 'access',
        'resource': 'role',
        'action': 'delete',
        'description': 'Allows deleting access roles.',
    },
    'access.role.assign_permissions': {
        'name': 'Assign role permissions',
        'module': 'access',
        'resource': 'role',
        'action': 'assign_permissions',
        'description': 'Allows assigning permissions to roles.',
    },
    'access.permission.view': {
        'name': 'View permissions',
        'module': 'access',
        'resource': 'permission',
        'action': 'view',
        'description': 'Allows viewing permission definitions.',
    },
    'access.user.view': {
        'name': 'View users',
        'module': 'access',
        'resource': 'user',
        'action': 'view',
        'description': 'Allows viewing user accounts.',
    },
    'access.user.create': {
        'name': 'Create users',
        'module': 'access',
        'resource': 'user',
        'action': 'create',
        'description': 'Allows creating user accounts.',
    },
    'access.user.update': {
        'name': 'Update users',
        'module': 'access',
        'resource': 'user',
        'action': 'update',
        'description': 'Allows updating user accounts.',
    },
    'access.user.delete': {
        'name': 'Delete users',
        'module': 'access',
        'resource': 'user',
        'action': 'delete',
        'description': 'Allows deleting user accounts.',
    },
    'access.user.assign_roles': {
        'name': 'Assign user roles',
        'module': 'access',
        'resource': 'user',
        'action': 'assign_roles',
        'description': 'Allows assigning roles to users.',
    },
    'access.user.assign_permissions': {
        'name': 'Assign direct permissions',
        'module': 'access',
        'resource': 'user',
        'action': 'assign_permissions',
        'description': 'Allows assigning direct permissions to users.',
    },
    'audit.log.view': {
        'name': 'View access audit logs',
        'module': 'audit',
        'resource': 'log',
        'action': 'view',
        'description': 'Allows viewing access-control audit logs.',
    },
    'customers.customer.view': {
        'name': 'View customers',
        'module': 'customers',
        'resource': 'customer',
        'action': 'view',
        'description': 'Allows viewing customers.',
    },
    'customers.customer.create': {
        'name': 'Create customers',
        'module': 'customers',
        'resource': 'customer',
        'action': 'create',
        'description': 'Allows creating customers.',
    },
    'customers.customer.update': {
        'name': 'Update customers',
        'module': 'customers',
        'resource': 'customer',
        'action': 'update',
        'description': 'Allows updating customers.',
    },
    'customers.customer.delete': {
        'name': 'Delete customers',
        'module': 'customers',
        'resource': 'customer',
        'action': 'delete',
        'description': 'Allows deleting customers.',
    },
    'inventory.category.view': {
        'name': 'View categories',
        'module': 'inventory',
        'resource': 'category',
        'action': 'view',
        'description': 'Allows viewing medicine categories.',
    },
    'inventory.category.create': {
        'name': 'Create categories',
        'module': 'inventory',
        'resource': 'category',
        'action': 'create',
        'description': 'Allows creating medicine categories.',
    },
    'inventory.category.update': {
        'name': 'Update categories',
        'module': 'inventory',
        'resource': 'category',
        'action': 'update',
        'description': 'Allows updating medicine categories.',
    },
    'inventory.category.delete': {
        'name': 'Delete categories',
        'module': 'inventory',
        'resource': 'category',
        'action': 'delete',
        'description': 'Allows deleting medicine categories.',
    },
    'inventory.medicine.view': {
        'name': 'View medicines',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'view',
        'description': 'Allows viewing medicines.',
    },
    'inventory.medicine.create': {
        'name': 'Create medicines',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'create',
        'description': 'Allows creating medicines.',
    },
    'inventory.medicine.update': {
        'name': 'Update medicines',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'update',
        'description': 'Allows updating medicines.',
    },
    'inventory.medicine.delete': {
        'name': 'Delete medicines',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'delete',
        'description': 'Allows deleting medicines.',
    },
    'inventory.medicine.adjust_stock': {
        'name': 'Adjust stock',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'adjust_stock',
        'description': 'Allows manually adjusting stock.',
    },
    'inventory.medicine.view_cost_price': {
        'name': 'View cost price',
        'module': 'inventory',
        'resource': 'medicine',
        'action': 'view_cost_price',
        'description': 'Allows viewing medicine cost price.',
    },
    'inventory.stock_transaction.view': {
        'name': 'View stock transactions',
        'module': 'inventory',
        'resource': 'stock_transaction',
        'action': 'view',
        'description': 'Allows viewing stock movement history.',
    },
    'procurement.supplier.view': {
        'name': 'View suppliers',
        'module': 'procurement',
        'resource': 'supplier',
        'action': 'view',
        'description': 'Allows viewing suppliers.',
    },
    'procurement.supplier.create': {
        'name': 'Create suppliers',
        'module': 'procurement',
        'resource': 'supplier',
        'action': 'create',
        'description': 'Allows creating suppliers.',
    },
    'procurement.supplier.update': {
        'name': 'Update suppliers',
        'module': 'procurement',
        'resource': 'supplier',
        'action': 'update',
        'description': 'Allows updating suppliers.',
    },
    'procurement.supplier.delete': {
        'name': 'Delete suppliers',
        'module': 'procurement',
        'resource': 'supplier',
        'action': 'delete',
        'description': 'Allows deleting suppliers.',
    },
    'procurement.purchase.view': {
        'name': 'View purchases',
        'module': 'procurement',
        'resource': 'purchase',
        'action': 'view',
        'description': 'Allows viewing purchases.',
    },
    'procurement.purchase.create': {
        'name': 'Create purchases',
        'module': 'procurement',
        'resource': 'purchase',
        'action': 'create',
        'description': 'Allows creating purchases.',
    },
    'procurement.purchase.update': {
        'name': 'Update purchases',
        'module': 'procurement',
        'resource': 'purchase',
        'action': 'update',
        'description': 'Allows updating purchases.',
    },
    'procurement.purchase.delete': {
        'name': 'Delete purchases',
        'module': 'procurement',
        'resource': 'purchase',
        'action': 'delete',
        'description': 'Allows deleting purchases.',
    },
    'procurement.purchase.receive_items': {
        'name': 'Receive purchase items',
        'module': 'procurement',
        'resource': 'purchase',
        'action': 'receive_items',
        'description': 'Allows marking purchased items as received.',
    },
    'sales.sale.view': {
        'name': 'View sales',
        'module': 'sales',
        'resource': 'sale',
        'action': 'view',
        'description': 'Allows viewing sales records.',
    },
    'sales.sale.create': {
        'name': 'Create sales',
        'module': 'sales',
        'resource': 'sale',
        'action': 'create',
        'description': 'Allows creating sales.',
    },
    'sales.sale.update': {
        'name': 'Update sales',
        'module': 'sales',
        'resource': 'sale',
        'action': 'update',
        'description': 'Allows updating sales.',
    },
    'sales.sale.delete': {
        'name': 'Delete sales',
        'module': 'sales',
        'resource': 'sale',
        'action': 'delete',
        'description': 'Allows deleting sales.',
    },
    'sales.sale.refund': {
        'name': 'Refund sales',
        'module': 'sales',
        'resource': 'sale',
        'action': 'refund',
        'description': 'Allows refunding sales.',
    },
    'sales.sale.process_payment': {
        'name': 'Process sale payment',
        'module': 'sales',
        'resource': 'sale',
        'action': 'process_payment',
        'description': 'Allows processing sale payments.',
    },
    'sales.sale.view_summary': {
        'name': 'View sale summaries',
        'module': 'sales',
        'resource': 'sale',
        'action': 'view_summary',
        'description': 'Allows viewing sales summaries.',
    },
    'sales.payment.view': {
        'name': 'View payments',
        'module': 'sales',
        'resource': 'payment',
        'action': 'view',
        'description': 'Allows viewing payments.',
    },
}


DEFAULT_ROLES = {
    'system_administrator': {
        'name': 'System Administrator',
        'description': 'Full dynamic access to the pharmacy platform.',
        'permissions': list(PERMISSIONS.keys()),
    },
    'pharmacist': {
        'name': 'Pharmacist',
        'description': 'Dispenses medicines and completes approved sales.',
        'permissions': [
            'customers.customer.view',
            'customers.customer.create',
            'inventory.category.view',
            'inventory.medicine.view',
            'sales.sale.view',
            'sales.sale.create',
            'sales.sale.process_payment',
            'sales.sale.view_summary',
            'sales.payment.view',
        ],
    },
    'cashier': {
        'name': 'Cashier',
        'description': 'Handles OTC sales and payment collection.',
        'permissions': [
            'customers.customer.view',
            'inventory.medicine.view',
            'sales.sale.view',
            'sales.sale.create',
            'sales.sale.process_payment',
            'sales.payment.view',
        ],
    },
}
