# Generated by Django 6.0 on 2025-12-23 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.medicine'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medicines_name_017048_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['category'], name='medicines_categor_dca1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['supplier'], name='medicines_supplie_a88547_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['expiry_date'], name='medicines_expiry__a56ade_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['stock_quantity'], name='medicines_stock_q_c2e274_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['batch_number'], name='medicines_batch_n_12ed66_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['barcode'], name='medicines_barcode_95be03_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['medicine'], name='stock_trans_medicin_86627b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_date'], name='stock_trans_transac_9087d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_trans_transac_b2b788_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_trans_referen_883dfe_idx'),
        ),
    ]
