# Generated by Django 6.0.6 on 2026-06-29 12:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicine_base_unit_and_more'),
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.medicinebatch'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cost_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_base_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_in_unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.medicineunitconversion'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
