# Generated by Codex on 2026-06-14

import django.db.models.deletion
from django.db import migrations, models


def seed_rbac(apps, schema_editor):
    from apps.users.permission_registry import DEFAULT_ROLES, PERMISSIONS

    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    PermissionProfile = apps.get_model('users', 'PermissionProfile')
    Role = apps.get_model('users', 'Role')
    User = apps.get_model('users', 'User')
    UserRoleAssignment = apps.get_model('users', 'UserRoleAssignment')

    role_content_type, _ = ContentType.objects.get_or_create(app_label='users', model='role')

    permissions_by_code = {}
    for codename, config in PERMISSIONS.items():
        permission, _ = Permission.objects.update_or_create(
            content_type=role_content_type,
            codename=codename,
            defaults={'name': config['name']},
        )
        PermissionProfile.objects.update_or_create(
            permission=permission,
            defaults={
                'module': config['module'],
                'resource': config['resource'],
                'action': config['action'],
                'description': config.get('description', ''),
                'is_active': True,
                'is_system': True,
                'is_assignable': True,
            },
        )
        permissions_by_code[codename] = permission

    for code, config in DEFAULT_ROLES.items():
        role, _ = Role.objects.update_or_create(
            code=code,
            defaults={
                'name': config['name'],
                'description': config.get('description', ''),
                'is_active': True,
                'is_system': True,
            },
        )
        role.permissions.set([permissions_by_code[item] for item in config['permissions'] if item in permissions_by_code])

    for role in Role.objects.filter(code=''):
        role.code = role.name.lower().replace(' ', '_')
        role.save(update_fields=['code'])

    for user in User.objects.exclude(role__isnull=True):
        UserRoleAssignment.objects.get_or_create(
            user=user,
            role=user.role,
            defaults={'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to='users.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='authorization_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_entries', to='users.user')),
                ('target_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='auth.permission')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='users.role')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_audit_targets', to='users.user')),
            ],
            options={
                'db_table': 'access_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('is_assignable', models.BooleanField(default=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.permission')),
            ],
            options={
                'db_table': 'permission_profiles',
                'ordering': ['module', 'resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='UserDirectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_direct_permissions', to='users.user')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_user_assignments', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_permission_assignments', to='users.user')),
            ],
            options={
                'db_table': 'user_direct_permissions',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_assignments', to='users.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='users.user')),
            ],
            options={
                'db_table': 'user_role_assignments',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='roles_code_4d7d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='accessauditlog',
            index=models.Index(fields=['action'], name='access_audi_action_cdf690_idx'),
        ),
        migrations.AddIndex(
            model_name='accessauditlog',
            index=models.Index(fields=['created_at'], name='access_audi_created_49e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionprofile',
            index=models.Index(fields=['module'], name='permission__module_61f445_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionprofile',
            index=models.Index(fields=['resource'], name='permission__resourc_22443e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionprofile',
            index=models.Index(fields=['action'], name='permission__action_18ec39_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionprofile',
            index=models.Index(fields=['is_active'], name='permission__is_acti_2db367_idx'),
        ),
        migrations.AddIndex(
            model_name='userdirectpermission',
            index=models.Index(fields=['user', 'is_active'], name='user_direc_user_id_0db130_idx'),
        ),
        migrations.AddIndex(
            model_name='userdirectpermission',
            index=models.Index(fields=['permission', 'is_active'], name='user_direc_permiss_0f5a22_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'is_active'], name='user_role_a_user_id_8994da_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['role', 'is_active'], name='user_role_a_role_id_9f01bc_idx'),
        ),
        migrations.RunPython(seed_rbac, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
