# Generated by Django 6.0.6 on 2026-06-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dynamic_rbac'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='access_audi_action_3e0ca8_idx',
            old_name='access_audi_action_cdf690_idx',
        ),
        migrations.RenameIndex(
            model_name='accessauditlog',
            new_name='access_audi_created_861550_idx',
            old_name='access_audi_created_49e78d_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionprofile',
            new_name='permission__module_dfc53b_idx',
            old_name='permission__module_61f445_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionprofile',
            new_name='permission__resourc_3ef492_idx',
            old_name='permission__resourc_22443e_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionprofile',
            new_name='permission__action_b52711_idx',
            old_name='permission__action_18ec39_idx',
        ),
        migrations.RenameIndex(
            model_name='permissionprofile',
            new_name='permission__is_acti_921275_idx',
            old_name='permission__is_acti_2db367_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='roles_code_25c050_idx',
            old_name='roles_code_4d7d4b_idx',
        ),
        migrations.RenameIndex(
            model_name='userdirectpermission',
            new_name='user_direct_user_id_f7c561_idx',
            old_name='user_direc_user_id_0db130_idx',
        ),
        migrations.RenameIndex(
            model_name='userdirectpermission',
            new_name='user_direct_permiss_406696_idx',
            old_name='user_direc_permiss_0f5a22_idx',
        ),
        migrations.RenameIndex(
            model_name='userroleassignment',
            new_name='user_role_a_user_id_c7b2be_idx',
            old_name='user_role_a_user_id_8994da_idx',
        ),
        migrations.RenameIndex(
            model_name='userroleassignment',
            new_name='user_role_a_role_id_5faa79_idx',
            old_name='user_role_a_role_id_9f01bc_idx',
        ),
    ]
