# Generated by Django 6.0.6 on 2026-06-29 12:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_change_reference_id_to_char'),
        ('suppliers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='base_unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('strips', 'Strips'), ('vials', 'Vials'), ('tubes', 'Tubes'), ('sachets', 'Sachets'), ('other', 'Other')], default='pieces', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='new_batch_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='previous_batch_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='quantity_base_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='quantity_in_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('strips', 'Strips'), ('vials', 'Vials'), ('tubes', 'Tubes'), ('sachets', 'Sachets'), ('other', 'Other')], default='pieces', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='new_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='previous_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('expired', 'Expired'), ('transfer', 'Transfer')], max_length=50),
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_batches', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'medicine_batches',
                'ordering': ['expiry_date', 'received_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.medicinebatch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transactions', to='inventory.medicinebatch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transactions', to='inventory.medicinebatch'),
        ),
        migrations.CreateModel(
            name='MedicineUnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=30)),
                ('factor_to_base_unit', models.PositiveIntegerField(help_text='How many base units are contained in one selected unit.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_base_unit', models.BooleanField(default=False)),
                ('allow_purchase', models.BooleanField(default=True)),
                ('allow_sale', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.medicine')),
            ],
            options={
                'db_table': 'medicine_unit_conversions',
                'ordering': ['sort_order', 'unit_name'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.medicineunitconversion'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['batch'], name='stock_trans_batch_i_011c53_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'expiry_date'], name='medicine_ba_medicin_ffbadf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'quantity_on_hand'], name='medicine_ba_medicin_4634d1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['batch_number'], name='medicine_ba_batch_n_cdced8_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['is_active'], name='medicine_ba_is_acti_94a323_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunitconversion',
            index=models.Index(fields=['medicine', 'is_active'], name='medicine_un_medicin_590e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicineunitconversion',
            index=models.Index(fields=['unit_name'], name='medicine_un_unit_na_b78643_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicineunitconversion',
            constraint=models.UniqueConstraint(fields=('medicine', 'unit_name'), name='uniq_medicine_unit_conversion'),
        ),
    ]
