# Generated by Django 6.0.6 on 2026-06-29 15:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def mark_legacy_piece_units_for_review(apps, schema_editor):
    Medicine = apps.get_model('inventory', 'Medicine')
    Medicine.objects.filter(base_unit='pieces').update(unit_review_required=True)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_batch_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='base_unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('strips', 'Strips'), ('vials', 'Vials'), ('tubes', 'Tubes'), ('sachets', 'Sachets'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('tablets', 'Tablets'), ('capsules', 'Capsules'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('strips', 'Strips'), ('vials', 'Vials'), ('tubes', 'Tubes'), ('sachets', 'Sachets'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(mark_legacy_piece_units_for_review, migrations.RunPython.noop),
    ]
